### ISSUE TITLE
S3 File not public

### ISSUE THREAD

**Issue by edit-michael** [tigrish/redmine_s3#1]
Hi,
is it possible that this plugin stored all files not public.
Regards
Michael

**Comment by tigrish** [comment]
I'll look into it, not sure what's involved tbh

**Comment by edit-michael** [comment]
it is a necessary feature for us. these files are not intended for third. 
Michael

**Comment by ballast** [comment]
We would like this feature too. We don't mind public to our redmine users, but definitely not public to the world. If the aws secret code could be stored encrypted that would be a bonus. Thanks in advance!

**Comment by ghost** [comment]
I have securized the s3 plugin for our own use. I believe the feature needs a configuration control of some kind before being posted as part of the core plugin, but I described the quick changes we performed on our installation: <a href="http://blog.fuery.com/2010/12/securing-redmines3-plugin.html">Securing the Redmine S3 Plugin</a>

Hope this is helpful.

**Comment by tigrish** [comment]
@fuery - this is awesome thank you very much for contributing!

I'll definitely put together a release with your changes as soon as I get a chance.

Thanks again :)

Chris
