### ISSUE TITLE
S3 plugin is incompatible with ChiliProject 3.0

### ISSUE THREAD

**Issue by nroach** [tigrish/redmine_s3#13]
The S3 plugin works with Redmine up to 1.3.x (untested on 1.4, but presumed working) and also works with ChiliProject up to 2.7.x.  However, ChiliProject 3.0.x introduces a new unified attachment scheme which breaks the S3 plugin.  

In briefly scanning through the CP3 source, it looks like the plugin will need to be updated, but shouldn't require a significant rewrite.  My company uses the s3 plugin and for us, s3 compatibility is mandatory due to our hosting situation, therefore the plugin incompatibility is a blocking issue for upgrading from 2.7 to 3.0.  I think we could contribute a little funding to a community effort or bounty to update the plugin, particularly if there is wider community interest in getting an update.

**Comment by tigrish** [comment]
Hi @nroach 

I haven't been using Redmine for quite some time now, even less so ChiliProject.

Unfortunately, this makes it hard for me to find the motivation to maintain this plugin. If you know of someone who would be willing to take over maintenance, I'd be more than happy to give them commit access to the repo.

Sorry, but I can't commit to spending any time on the development of this project.
