### ISSUE TITLE
Redmine 2.4, 2.5

### ISSUE THREAD

**Issue by krzaczek** [tigrish/redmine_s3#15]
Any chance to upgrade this module to work with Redmine 2.5 ?

**Comment by cerw** [comment]
+1

**Comment by tigrish** [comment]
I haven't used Redmine in years - does anybody want to update this module?

**Comment by return1** [comment]
you should take a look at https://github.com/ka8725/redmine_s3 , which works for Redmine 2.4 and 2.5

**Comment by krzaczek** [comment]
@return1 thx for the info
